/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as TermsOfServiceRouteImport } from "./routes/terms-of-service"
import { Route as SitemapDotxmlRouteImport } from "./routes/sitemap[.]xml"
import { Route as RobotsDottxtRouteImport } from "./routes/robots[.]txt"
import { Route as PrivacyPolicyRouteImport } from "./routes/privacy-policy"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as PreviewIndexRouteImport } from "./routes/preview/index"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AccountIndexRouteImport } from "./routes/account/index"
import { Route as ProductsSlugIdRouteImport } from "./routes/products/$slugId"
import { Route as PreviewV3RouteImport } from "./routes/preview/v3"
import { Route as PreviewV2RouteImport } from "./routes/preview/v2"
import { Route as PreviewV1RouteImport } from "./routes/preview/v1"
import { Route as PaymentCallbackRouteImport } from "./routes/payment/callback"
import { Route as ApiSplatRouteImport } from "./routes/api/$"
import { Route as AdminStorefrontRouteImport } from "./routes/admin/storefront"
import { Route as AdminLoginRouteImport } from "./routes/admin/login"
import { Route as AccountVerifyEmailRouteImport } from "./routes/account/verify-email"
import { Route as AccountLoginRouteImport } from "./routes/account/login"

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: "/terms-of-service",
  path: "/terms-of-service",
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: "/sitemap.xml",
  path: "/sitemap.xml",
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: "/robots.txt",
  path: "/robots.txt",
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: "/privacy-policy",
  path: "/privacy-policy",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewIndexRoute = PreviewIndexRouteImport.update({
  id: "/preview/",
  path: "/preview/",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: "/account/",
  path: "/account/",
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugIdRoute = ProductsSlugIdRouteImport.update({
  id: "/products/$slugId",
  path: "/products/$slugId",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewV3Route = PreviewV3RouteImport.update({
  id: "/preview/v3",
  path: "/preview/v3",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewV2Route = PreviewV2RouteImport.update({
  id: "/preview/v2",
  path: "/preview/v2",
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewV1Route = PreviewV1RouteImport.update({
  id: "/preview/v1",
  path: "/preview/v1",
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCallbackRoute = PaymentCallbackRouteImport.update({
  id: "/payment/callback",
  path: "/payment/callback",
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStorefrontRoute = AdminStorefrontRouteImport.update({
  id: "/admin/storefront",
  path: "/admin/storefront",
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: "/admin/login",
  path: "/admin/login",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: "/account/verify-email",
  path: "/account/verify-email",
  getParentRoute: () => rootRouteImport,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: "/account/login",
  path: "/account/login",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/robots.txt": typeof RobotsDottxtRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms-of-service": typeof TermsOfServiceRoute
  "/account/login": typeof AccountLoginRoute
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/storefront": typeof AdminStorefrontRoute
  "/api/$": typeof ApiSplatRoute
  "/payment/callback": typeof PaymentCallbackRoute
  "/preview/v1": typeof PreviewV1Route
  "/preview/v2": typeof PreviewV2Route
  "/preview/v3": typeof PreviewV3Route
  "/products/$slugId": typeof ProductsSlugIdRoute
  "/account/": typeof AccountIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/preview/": typeof PreviewIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/robots.txt": typeof RobotsDottxtRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms-of-service": typeof TermsOfServiceRoute
  "/account/login": typeof AccountLoginRoute
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/storefront": typeof AdminStorefrontRoute
  "/api/$": typeof ApiSplatRoute
  "/payment/callback": typeof PaymentCallbackRoute
  "/preview/v1": typeof PreviewV1Route
  "/preview/v2": typeof PreviewV2Route
  "/preview/v3": typeof PreviewV3Route
  "/products/$slugId": typeof ProductsSlugIdRoute
  "/account": typeof AccountIndexRoute
  "/admin": typeof AdminIndexRoute
  "/preview": typeof PreviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/privacy-policy": typeof PrivacyPolicyRoute
  "/robots.txt": typeof RobotsDottxtRoute
  "/sitemap.xml": typeof SitemapDotxmlRoute
  "/terms-of-service": typeof TermsOfServiceRoute
  "/account/login": typeof AccountLoginRoute
  "/account/verify-email": typeof AccountVerifyEmailRoute
  "/admin/login": typeof AdminLoginRoute
  "/admin/storefront": typeof AdminStorefrontRoute
  "/api/$": typeof ApiSplatRoute
  "/payment/callback": typeof PaymentCallbackRoute
  "/preview/v1": typeof PreviewV1Route
  "/preview/v2": typeof PreviewV2Route
  "/preview/v3": typeof PreviewV3Route
  "/products/$slugId": typeof ProductsSlugIdRoute
  "/account/": typeof AccountIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/preview/": typeof PreviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/privacy-policy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/account/login"
    | "/account/verify-email"
    | "/admin/login"
    | "/admin/storefront"
    | "/api/$"
    | "/payment/callback"
    | "/preview/v1"
    | "/preview/v2"
    | "/preview/v3"
    | "/products/$slugId"
    | "/account/"
    | "/admin/"
    | "/preview/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/privacy-policy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/account/login"
    | "/account/verify-email"
    | "/admin/login"
    | "/admin/storefront"
    | "/api/$"
    | "/payment/callback"
    | "/preview/v1"
    | "/preview/v2"
    | "/preview/v3"
    | "/products/$slugId"
    | "/account"
    | "/admin"
    | "/preview"
  id:
    | "__root__"
    | "/"
    | "/privacy-policy"
    | "/robots.txt"
    | "/sitemap.xml"
    | "/terms-of-service"
    | "/account/login"
    | "/account/verify-email"
    | "/admin/login"
    | "/admin/storefront"
    | "/api/$"
    | "/payment/callback"
    | "/preview/v1"
    | "/preview/v2"
    | "/preview/v3"
    | "/products/$slugId"
    | "/account/"
    | "/admin/"
    | "/preview/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminStorefrontRoute: typeof AdminStorefrontRoute
  ApiSplatRoute: typeof ApiSplatRoute
  PaymentCallbackRoute: typeof PaymentCallbackRoute
  PreviewV1Route: typeof PreviewV1Route
  PreviewV2Route: typeof PreviewV2Route
  PreviewV3Route: typeof PreviewV3Route
  ProductsSlugIdRoute: typeof ProductsSlugIdRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  PreviewIndexRoute: typeof PreviewIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/terms-of-service": {
      id: "/terms-of-service"
      path: "/terms-of-service"
      fullPath: "/terms-of-service"
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/sitemap.xml": {
      id: "/sitemap.xml"
      path: "/sitemap.xml"
      fullPath: "/sitemap.xml"
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/robots.txt": {
      id: "/robots.txt"
      path: "/robots.txt"
      fullPath: "/robots.txt"
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/privacy-policy": {
      id: "/privacy-policy"
      path: "/privacy-policy"
      fullPath: "/privacy-policy"
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview/": {
      id: "/preview/"
      path: "/preview"
      fullPath: "/preview/"
      preLoaderRoute: typeof PreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin/"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account/": {
      id: "/account/"
      path: "/account"
      fullPath: "/account/"
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/products/$slugId": {
      id: "/products/$slugId"
      path: "/products/$slugId"
      fullPath: "/products/$slugId"
      preLoaderRoute: typeof ProductsSlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview/v3": {
      id: "/preview/v3"
      path: "/preview/v3"
      fullPath: "/preview/v3"
      preLoaderRoute: typeof PreviewV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview/v2": {
      id: "/preview/v2"
      path: "/preview/v2"
      fullPath: "/preview/v2"
      preLoaderRoute: typeof PreviewV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/preview/v1": {
      id: "/preview/v1"
      path: "/preview/v1"
      fullPath: "/preview/v1"
      preLoaderRoute: typeof PreviewV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    "/payment/callback": {
      id: "/payment/callback"
      path: "/payment/callback"
      fullPath: "/payment/callback"
      preLoaderRoute: typeof PaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/api/$": {
      id: "/api/$"
      path: "/api/$"
      fullPath: "/api/$"
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/storefront": {
      id: "/admin/storefront"
      path: "/admin/storefront"
      fullPath: "/admin/storefront"
      preLoaderRoute: typeof AdminStorefrontRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/admin/login": {
      id: "/admin/login"
      path: "/admin/login"
      fullPath: "/admin/login"
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account/verify-email": {
      id: "/account/verify-email"
      path: "/account/verify-email"
      fullPath: "/account/verify-email"
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/account/login": {
      id: "/account/login"
      path: "/account/login"
      fullPath: "/account/login"
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountVerifyEmailRoute: AccountVerifyEmailRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminStorefrontRoute: AdminStorefrontRoute,
  ApiSplatRoute: ApiSplatRoute,
  PaymentCallbackRoute: PaymentCallbackRoute,
  PreviewV1Route: PreviewV1Route,
  PreviewV2Route: PreviewV2Route,
  PreviewV3Route: PreviewV3Route,
  ProductsSlugIdRoute: ProductsSlugIdRoute,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  PreviewIndexRoute: PreviewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from "./router.tsx"
import type { createStart } from "@tanstack/react-start"
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
